# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.2.0

# Filters to ensure this only runs on tags for a release
prod_release_filters: &prod_release_filters
  filters:
    tags:
      only: /^v[0-9]+(\.[0-9]+)*$/

jobs:
  install-node:
    executor: node/default
    steps:
      - run: sudo npm install -g npm@latest

  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Netlify CLI
          command: npm install netlify-cli@17.10.1 -g
      - node/install-packages
      - run:
          name: Build
          command: npm run build

  deploy:
    executor:
      name: node/default
    steps:
      - build
      - run:
          name: Deploy to Netlify
          command: |
            netlify deploy \
            --dir build \
            --site $NETLIFY_SITE_ID \
            --auth $NETLIFY_API_TOKEN \
#            --prod