# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

config_blocks:
  prod_filters: &prod_filters
    filters:
      tags:
        only:
          - /^v[0-9]+(\.[0-9]+)*$/
      branches:
        ignore: /.*/

  staging_filters: &staging_filters
    filters:
      branches:
        only: main

  config_defaults: &config_defaults
    docker:
      - image: cimg/node:21.7.3

commands:
  step_defaults:
    steps:
      - run:
          name: Install pnpm
          command: sudo npm install -g pnpm@9
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}-{{ .Branch }}
      - run:
          name: Install
          command: pnpm install   # Running this here even if it is a dependency on all workflows to ensure things are run correctly

jobs:
  build_branch:
    <<: *config_defaults
    steps:
      - step_defaults
      - run:
          name: Deploy
          command: |
            ./node_modules/.bin/netlify deploy --build --dir=build --site $NETLIFY_SITE_ID --auth $NETLIFY_API_TOKEN
      - save_cache:
          key: platform-build-cache-{{ .Branch }}
          paths:
            - ./build

  build_staging:
    <<: *config_defaults
    steps:
      - step_defaults
      - run:
          name: Deploy Staging
          command: |
            ./node_modules/.bin/netlify deploy --build --dir=build --site $NETLIFY_SITE_ID --auth $NETLIFY_API_TOKEN
      - save_cache:
          key: platform-build-cache-{{ .Branch }}
          paths:
            - ./build

  tag_release:
    <<: *config_defaults
    steps:
      - step_defaults
      - run:
          name: Add GitHub to SSH
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Bp5aw4/oi7aVAS2YbucqiRyPZDOTIzM8CFJvHqIgqhM"
      - run:
          name: Create Identity
          command: |
            git config --global user.email "circleci@audiostack.com"
            git config --global user.name "CircleCI"
      - run:
          name: Tag Release
          command: bash scripts/makeRelease.sh

  build_prod:
    <<: *config_defaults
    steps:
      - step_defaults
      - run:
          name: Build and Deploy
          command: ./node_modules/.bin/netlify deploy --build --dir=build --site $NETLIFY_SITE_ID --prod --auth $NETLIFY_API_TOKEN
      - save_cache:
          key: platform-build-cache-{{ .Branch }}
          paths:
            - ./build

workflows:
  version: 2
  branch:
    jobs:
      - build_branch:
          name: Build Branch

  staging:
    jobs:
      - build_staging:
          name: Build Staging
          <<: *staging_filters
      - make_release:
          name: Make Release
          type: approval
          requires:
            - Build Staging
      - tag_release:
          name: Tag Release
          requires:
            - Make Release

  prod:
    jobs:
      - build_prod:
          name: Build Prod
          filters:
            tags:
              only:
                - /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/